package com.app.GUI.components;

import com.app.DAO.AnswerDAO;
import com.app.DAO.ExamDAO;

import com.app.DAO.QuestionDAO;
import com.app.Models.Answer;
import com.app.Models.Questions;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class QuestionPanels extends JPanel {
    private int id;
    private JPanel panel1;

    public QuestionPanels(int id, int qIndex) {
        this.id = id;
        $$$setupUI$$$();
        loadData(id, qIndex);
        add(panel1);// Ensure panel1 is initialized


    }

    private void loadData(int id, int qIndex) {
        Questions question = QuestionDAO.getQuestionById(id);
        ArrayList<Answer> answers = AnswerDAO.getAnswersByqId(id);

        panel1 = new JPanel();

        // Define FormLayout with vertical spacing
        StringBuilder rowSpec = new StringBuilder("10dlu, pref, 10dlu, pref, 20dlu"); // Space before question
        for (int i = 0; i < answers.size(); i++) {
            rowSpec.append(", 50dlu, pref"); // Add 10dlu spacing before each answer
        }

        panel1.setLayout(new FormLayout(
                "15dlu, pref, 15dlu",  // Horizontal layout
                rowSpec.toString()      // Dynamically generated vertical layout
        ));

        CellConstraints cc = new CellConstraints();

        // Add question title and content
        panel1.add(new JLabel("Question " + qIndex), cc.xy(2, 2));
        panel1.add(new JLabel(question.getqContent()), cc.xy(2, 4));

        int index = 6; // Start at row 6 for answers
        ButtonGroup answerGroup = new ButtonGroup();

        for (Answer answer : answers) {
            JRadioButton answerButton = new JRadioButton(answer.getaContent());
            answerGroup.add(answerButton);
            panel1.add(answerButton, cc.xy(2, index));
            index += 2; // Move to the next row, skipping a row for spacing (10dlu)
        }

        panel1.revalidate();
        panel1.repaint();
    }



    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("", ""));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
