package com.app.GUI.components;

import com.app.DAO.AnswerDAO;
import com.app.DAO.ExamDAO;

import com.app.DAO.QuestionDAO;
import com.app.Models.Answer;
import com.app.Models.Questions;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class QuestionPanels extends JPanel {
    private int id;
    private JPanel panel1;

    public QuestionPanels(int id) {
        this.id = id;
        $$$setupUI$$$();
        loadData(id);
        add(panel1);// Ensure panel1 is initialized


    }

    private void loadData(int id) {
        Questions question = QuestionDAO.getQuestionById(id);
        ArrayList<Answer> answers = AnswerDAO.getAnswersByqId(id);
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("pref", "pref"));
        String columnSpec = "pref";
        // Define rows dynamically (1 for question + answers count)
        String rowSpec = "pref";
        for (int i = 0; i < answers.size(); i++) {
            rowSpec += ", pref";
        }
        CellConstraints cc = new CellConstraints();
        panel1.setLayout(new FormLayout("pref", "pref,pref,pref,pref"));
        panel1.add(new JLabel(question.getqContent()), cc.xy(1, 1));
        int index = 2;
        for (Answer answer : answers) {
            panel1.add(new JRadioButton(answer.getaContent()), cc.xy(1, index));
            index++;
        }
        panel1.revalidate(); // Refresh UI layout
        panel1.repaint();


    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("", ""));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
