package com.app.GUI.components;

import com.app.DAO.AnswerDAO;
import com.app.DAO.ExamDAO;

import com.app.DAO.QuestionDAO;
import com.app.Models.Answer;
import com.app.Models.Questions;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

public class QuestionPanels extends JPanel {
    private int id;
    private JPanel panel1;
    private int selectedAnswer = -1;

    public QuestionPanels(int id, int qIndex) {
        this.id = id;
        $$$setupUI$$$();
        loadData(id, qIndex);
        add(panel1);// Ensure panel1 is initialized


    }

    private void loadData(int id, int qIndex) {
        Questions question = QuestionDAO.getQuestionById(id);
        ArrayList<Answer> answers = AnswerDAO.getAnswersByqId(id);

        panel1 = new JPanel();
        panel1.setLayout(new FormLayout(
                "30dlu, 10dlu, pref:grow, 30dlu",  // More columns for spacing
                "10dlu, pref, 10dlu, pref, 20dlu" + ", 50dlu, pref".repeat(answers.size())
        ));

        CellConstraints cc = new CellConstraints();

        // Define fonts
        Font questionFont = new Font("Arial", Font.BOLD, 18); // Bigger & bold question
        Font answerFont = new Font("Arial", Font.PLAIN, 16);  // Larger answer text

        // Add question title and content
        JLabel questionLabel = new JLabel("Question " + qIndex);
        questionLabel.setFont(questionFont);
        panel1.add(questionLabel, cc.xy(3, 2)); // Shifted to the right

        JLabel contentLabel = new JLabel(question.getqContent());
        contentLabel.setFont(questionFont);
        panel1.add(contentLabel, cc.xy(3, 4)); // Shifted to the right

        int index = 6; // Start at row 6 for answers
        ButtonGroup answerGroup = new ButtonGroup();

        for (Answer answer : answers) {
            JRadioButton answerButton = new JRadioButton(answer.getaContent());
            answerButton.setFont(answerFont); // Apply font to radio buttons
            answerGroup.add(answerButton);
            answerButton.addActionListener(e -> {
                selectedAnswer = answer.getaId();
                System.out.println("-> Selected Answer: " + selectedAnswer);
            });
            panel1.add(answerButton, cc.xy(3, index)); // Shifted to the right
            index += 2;
        }

        panel1.revalidate();
        panel1.repaint();
    }

    public int getSelectedAnswer() {
        return selectedAnswer;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new FormLayout("", ""));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
