package com.app.GUI.components;

import javax.swing.*;
import java.awt.*;

import com.app.Models.Exams;
import com.jgoodies.forms.layout.*;

public class UserTest extends JFrame {
    private JPanel contentPanel;
    private JButton previousButton;
    private JButton nextButton;
    private JButton submitButton;
    private JPanel mainContentPanel;
    private JPanel panel;
    private JPanel panel_1;
    private JButton btnNewButton;
    private JButton btnNewButton_1;
    private JButton btnNewButton_2;
    private JRadioButton radioButton;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
    private JRadioButton rdbtnNewRadioButton;
    private JRadioButton rdbtnNewRadioButton_1;
    private JTextField textField;
    private Exams exam;

    public UserTest() {
        setContentPane(contentPanel);
        setSize(500, 600);
        setVisible(true);
        CardLayout layout = new CardLayout();
        mainContentPanel.setLayout(layout);
        mainContentPanel.add(new QuestionPanels(1, 1), "question");
        layout.show(mainContentPanel, "question");
        revalidate();
        repaint();
    }

    private void loadQuestionsPanels() {


    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new FormLayout("right:100px:noGrow,left:5px:noGrow,fill:300px:noGrow,fill:100px:noGrow", "center:261px:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        nextButton = new JButton();
        nextButton.setText("Next");
        CellConstraints cc = new CellConstraints();
        contentPanel.add(nextButton, cc.xy(4, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        submitButton = new JButton();
        submitButton.setText("Submit");
        contentPanel.add(submitButton, cc.xyw(2, 3, 2, CellConstraints.CENTER, CellConstraints.DEFAULT));
        previousButton = new JButton();
        previousButton.setText("Previous");
        contentPanel.add(previousButton, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        mainContentPanel = new JPanel();
        mainContentPanel.setLayout(new CardLayout(0, 0));
        contentPanel.add(mainContentPanel, cc.xyw(1, 1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}

