package com.app.GUI.components;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.HashMap;

import com.app.DAO.AnswerDAO;
import com.app.DAO.ResultDAO;
import com.app.Models.Exams;
import com.app.Models.Result;
import com.jgoodies.forms.layout.*;

public class UserTest extends JFrame {
    private JPanel contentPanel;
    private JButton previousButton;
    private JButton nextButton;
    private JButton submitButton;
    private JPanel mainContentPanel;
    private JPanel panel;
    private JPanel panel_1;
    private JButton btnNewButton;
    private JButton btnNewButton_1;
    private JButton btnNewButton_2;
    private JRadioButton radioButton;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
    private JRadioButton rdbtnNewRadioButton;
    private JRadioButton rdbtnNewRadioButton_1;
    private JTextField textField;
    private Exams currentExam;
    private int currentIndex = 0;
    private ArrayList<QuestionPanels> questionPanels = new ArrayList<>();

    public UserTest(Exams exam) {
        currentExam = exam;
        setContentPane(contentPanel);
        setSize(500, 600);
        setVisible(true);
        CardLayout layout = new CardLayout();
        mainContentPanel.setLayout(layout);
        loadQuestionsPanels();
        revalidate();
        repaint();
        nextButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                layout.next(mainContentPanel);
            }
        });
        previousButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                layout.previous(mainContentPanel);
            }
        });
        submitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    private void loadQuestionsPanels() {
        int index = 1;
        for (int i : currentExam.getQuesIDs()) {
            QuestionPanels qp = new QuestionPanels(i, index);
            questionPanels.add(qp);
            mainContentPanel.add(qp);
            index++;
        }
        mainContentPanel.revalidate();
        mainContentPanel.repaint();
    }
    private ArrayList<Integer>  getAnswers(){
       ArrayList<Integer> answers = new ArrayList<>();
        for (QuestionPanels qp : questionPanels) {
            int selectedAnswer = qp.getSelectedAnswer();
            if (selectedAnswer == -1) {
                answers.add(0);
            }
            else {
                answers.add(selectedAnswer);
            }
        }
        return answers;
    }
    private void createResults(ArrayList<Integer> answers){
        StringBuilder result = new StringBuilder();
        int correctAnswer = 0;
        for (int value : answers) {
            if (result.length() > 0) {
                result.append(",");
            }
            result.append(value);
            if (AnswerDAO.getAnswerById(value).isRight()){
                correctAnswer++;
            }
        }
        double mark =  (double) correctAnswer / answers.size();
        System.out.println(result.toString());
        int rsNum = ResultDAO.getLatestRsNum(1,currentExam.getExCode());


    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new FormLayout("right:100px:noGrow,left:5px:noGrow,fill:300px:noGrow,fill:100px:noGrow", "center:261px:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        nextButton = new JButton();
        nextButton.setText("Next");
        CellConstraints cc = new CellConstraints();
        contentPanel.add(nextButton, cc.xy(4, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        submitButton = new JButton();
        submitButton.setText("Submit");
        contentPanel.add(submitButton, cc.xyw(2, 3, 2, CellConstraints.CENTER, CellConstraints.DEFAULT));
        previousButton = new JButton();
        previousButton.setText("Previous");
        contentPanel.add(previousButton, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
        mainContentPanel = new JPanel();
        mainContentPanel.setLayout(new CardLayout(0, 0));
        contentPanel.add(mainContentPanel, cc.xyw(1, 1, 3));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}

