package com.app.GUI.components;

import javax.swing.*;
import java.awt.*;

import com.app.Models.Exams;
import com.jgoodies.forms.layout.*;

public class UserTest extends JFrame {
    private JPanel contentPanel;
    private JButton button1;
    private JButton button2;
    private JButton button3;
    private JPanel mainContentPanel;
    private JPanel panel;
    private JPanel panel_1;
    private JButton btnNewButton;
    private JButton btnNewButton_1;
    private JButton btnNewButton_2;
    private JRadioButton radioButton;
    private JLabel lblNewLabel;
    private JLabel lblNewLabel_1;
    private JRadioButton rdbtnNewRadioButton;
    private JRadioButton rdbtnNewRadioButton_1;
    private JTextField textField;
    private Exams exam;

    public UserTest() {
        setContentPane(contentPanel);
        setSize(700, 800);
        setVisible(true);
        CardLayout layout = new CardLayout();
        mainContentPanel.setLayout(layout);
        mainContentPanel.add(new QuestionPanels(1), "question");
        layout.show(mainContentPanel, "question");
        revalidate();
        repaint();
    }

    private void loadQuestionsPanels() {


    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPanel = new JPanel();
        contentPanel.setLayout(new FormLayout("right:100px:noGrow,left:6dlu:noGrow,fill:100px:noGrow,left:4dlu:noGrow,fill:100px:noGrow", "center:261px:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        mainContentPanel = new JPanel();
        mainContentPanel.setLayout(new CardLayout(0, 0));
        CellConstraints cc = new CellConstraints();
        contentPanel.add(mainContentPanel, cc.xyw(1, 1, 5));
        button2 = new JButton();
        button2.setText("Button");
        contentPanel.add(button2, cc.xy(5, 3));
        button3 = new JButton();
        button3.setText("Button");
        contentPanel.add(button3, cc.xy(3, 3));
        button1 = new JButton();
        button1.setText("Button");
        contentPanel.add(button1, cc.xy(1, 3, CellConstraints.CENTER, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPanel;
    }

}

